name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/actions/init"
      - name: Check
        run: |
          cargo check --release --tests

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/actions/init"
      - name: Install nightly rustfmt
        run: rustup toolchain install nightly --component rustfmt 
      - name: Fmt
        run: |
          cargo +nightly fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/actions/init"
      - name: Clippy
        run: |
          cargo clippy -- -D warnings

  tests:
    runs-on: ubuntu-latest
    needs: [check, fmt]
    env: 
      SAMPLE_FILES_PATH: "$(pwd)/test_builder/sample_files"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/actions/init"
      - name: Set sample files path env variable
        run: echo "SAMPLE_FILES_PATH=$(pwd)/test_builder/sample_files" >> $GITHUB_ENV
      - name: Run tests
        run: |
          cargo test --tests

  doc-tests:
    runs-on: ubuntu-latest
    needs: [check, fmt]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/actions/init"
      - name: Run doc tests
        run: |
          cargo test --doc

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    env:
      SAMPLE_FILES_PATH: "$(pwd)/test_builder/sample_files"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/actions/init"
      - name: Install nightly llvm-tools-preview
        run: rustup toolchain install nightly --component llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Set sample files path env variable
        run: echo "SAMPLE_FILES_PATH=$(pwd)/test_builder/sample_files" >> $GITHUB_ENV
      - name: Generate code coverage
        run: |
          cargo llvm-cov \
          --codecov \
          --ignore-filename-regex ".*test.*\.rs$" \
          --output-path cov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cov.json
          fail_ci_if_error: true
